import type { Metadata } from "next";
import { Inter, Outfit, Roboto } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ['400', '500', '700'], // Specify the weights you need
  subsets: ['latin'],
  variable: '--font-roboto', // This creates a CSS variable
});

export const metadata: Metadata = {
  title: "WritePro",
  description: "Generated by Umair Ahmed",
  icons: {
    icon: "/logo.svg",
    shortcut: "/logo.svg",
    apple: "/logo.svg",
    other: {
      rel: "apple-touch-icon-precomposed",
      url: "/logo.svg",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.className} ${roboto.variable}`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}